// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVNYkmk1OsIPlrSdsXTrvlltJ_beh8ipM',
    appId: '1:321656771163:android:b558ca01137cb99ffae57e',
    messagingSenderId: '321656771163',
    projectId: 'kbo-baseball-diary',
    storageBucket: 'kbo-baseball-diary.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq24EF4GRV4LQ6_rk7nqfZs1FPMpwg47Y',
    appId: '1:321656771163:ios:861d1103f4ca53a7fae57e',
    messagingSenderId: '321656771163',
    projectId: 'kbo-baseball-diary',
    storageBucket: 'kbo-baseball-diary.firebasestorage.app',
    iosBundleId: 'com.example.baseballDiary',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHdwIWzBxFOxhUAWifTLr47VtfNXlmj0o',
    appId: '1:321656771163:web:99e58f618e4ad69dfae57e',
    messagingSenderId: '321656771163',
    projectId: 'kbo-baseball-diary',
    authDomain: 'kbo-baseball-diary.firebaseapp.com',
    storageBucket: 'kbo-baseball-diary.firebasestorage.app',
  );

}